{
 "title": "Fibo requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Fibo Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(fibo_controller_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Fibo input",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "fibo_controller_input" }
   ]
  },
  {
   "title": "Execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(fibo_execution_time_seconds_count[$__rate_interval])"
    }
   ]
  }
 ]
}